# Generated by Django 5.1.7 on 2025-03-28 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('pickup_hours', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('max_price_limit', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
